name: Protobuf CI

on:
  workflow_call:
    inputs:
      proto-admin-team:
        description: Team that can bypass breakings
        type: string
        default: agglayer-developers
      detect-breakings:
        description: Defines if breakings need to be checked
        type: boolean
        default: false
      breaking-ref:
        description: Ref used to detect breakings
        type: string
        default: branch=main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: true

      - name: Checking for build success
        run: buf build --error-format=github-actions proto

      - name: Checking for lint issues
        run: buf lint --error-format=github-actions proto

      - name: Checking format
        run: buf format --error-format=github-actions proto

  generated-file-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}

      - name: Save initial state of proto-related files
        run: git status --porcelain crates > before.txt

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Generate cache key
        id: cache_key
        run: echo "key=${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}" >> $GITHUB_OUTPUT

      - name: Set up rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ steps.cache_key.outputs.key }}

      - name: Install cargo-make
        run: cargo install --debug --locked cargo-make

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: true

      - name: Generate protobuf sources
        run: cargo make generate-proto

      - name: Check for modifications
        run: |
          git status --porcelain crates > after.txt
          if ! diff before.txt after.txt > /dev/null; then
            echo "âŒ Running 'cargo make generate-proto' modified some files! Ensure everything is committed."
            git diff crates
            exit 1
          fi

  breaking-changes:
    runs-on: ubuntu-latest
    if: ${{ inputs.detect-breakings }}
    env: BREAKING_REF=${{ inputs.breaking-ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}

      - name: Define BREAKING_REF for merge_group
        if: github.event_name == 'merge_group'
        run: echo "BREAKING_REF=ref=${{ github.event.merge_group.base_sha }}" >> $GITHUB_ENV

      - name: Define BREAKING_REF for pull_request
        if: github.event_name == 'pull_request'
        run: echo "BREAKING_REF=ref=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

        # Check if the retry attempt is by an admin
        # If it is, it will trigger an approval
      - name: Check retry attempt by admin
        id: authorized_list
        if: ${{ github.run_attempt > 1 }}
        uses: morfien101/actions-authorized-user@v3
        with:
          username: ${{ github.triggering_actor }}
          org: agglayer
          team: ${{ inputs.proto_admin_team }}
          github_token: ${{ secrets.TEAM_READ_GH_TOKEN }}
          multi_user: false

      - name: Breaking changes detection
        uses: bufbuild/buf-action@v1
        id: breaking
        # Ignoring breaking as if a breaking arrives on main, it has been approved before.
        if: github.event_name != 'push' && env.PROTO_BREAKING_DETECTION == 'true'
        # Make this job continue-on-error if:
        #   - the authorized attempt is true. See authorized step
        #   - The job is in merge_queue as if a breaking is detected, an approval will be asked to admins
        continue-on-error: ${{ steps.authorized_list.outputs.authorized == 'true' || github.event_name == 'merge_group' }}
        with:
          token: ${{ secrets.BUF_TOKEN }}
          input: proto
          breaking_against: "${{ github.event.repository.clone_url }}#format=git,${{ env.BREAKING_REF }},subdir=proto"
          breaking: true

      - name: Wait for approval
        if: ${{ (steps.authorized_list.outputs.authorized == 'true' || github.event_name == 'merge_group') && steps.breaking.outcome == 'failure' }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TEAM_READ_GH_TOKEN }}
          issue-title: "Breaking changes attempt on protobuf definition"
          issue-body: "Please approve or deny the breaking changes"
          approvers: agglayer-admins
          minimum-approvals: 1
